run:
  deadline: 10m

  concurrency: 4

#  skip-dirs:
#  - vendor/

#  skip-files:

linters:
  disable-all: true
  fast: false
  enable:
  - goimports
  - golint
  - govet
  - gofmt
  - structcheck
  - staticcheck
  - varcheck
  - interfacer
  - unconvert
  - ineffassign
  - goconst
  - misspell
  - nakedret
  - deadcode

issues:
  max-issues-per-linter: 100
  max-same-issues: 50
